# -*- coding: utf-8 -*-
"""TC52_visualization1&2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MTTyHpyL29zfXcyqsuWQuLy4Ru3FlQ_l
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""Importing and Displaying Data"""

df = sns.load_dataset('titanic')
df.head()

df.shape

df.describe()

"""Checking Null Values"""

df.isnull().sum()

"""Data preprocessing"""

df.drop('age', axis=1, inplace= True)

df.drop('deck', axis = 1, inplace = True)

df.drop('embarked', axis = 1, inplace = True)

df

df.isnull().sum()

sns.histplot(data = df, x = 'fare', binwidth=30)

sns.histplot(data = df, x ='fare', kde=True, binwidth = 30)

sns.histplot(data = df, x ='fare', hue= 'pclass', binwidth=25 )

sns.histplot(data= df, x='sex', hue='alive', binwidth=30)

sns.histplot(data = df, x = 'fare', hue='sex', binwidth=30)

sns.distplot(df['fare'])

sns.distplot(df['fare'], kde= False, bins= 15)

sns.displot(data=df, x= 'fare', multiple = 'dodge', col= 'pclass', binwidth=24)

sns.displot(data=df, x='fare', col= 'pclass', hue='sex', multiple ='dodge', binwidth=25)

"""Assingment 2 visualization"""

df1 = sns.load_dataset('titanic')

df1['age'].fillna(df1['age'].mean(), inplace = True)

df1.drop('deck', axis = 1, inplace = True)

df1.drop('embarked', axis = 1, inplace = True)
df1.drop('embark_town', axis = 1, inplace = True)

df1.isnull().sum()

sns.boxplot(x = 'sex' , y= 'age', data=df1)

sns.boxplot(x = 'age' , y= 'sex', hue='survived', data=df1)

sns.boxplot(x = 'age' , y= 'sex', data=df1)

sns.boxplot(x= 'age', y='sex', hue='survived', data=df1)

sns.barplot(x='sex', y='age', data=df1)

sns.barplot(x='pclass', y='age', data=df1)

sns.barplot(x='sex', y='age', hue='pclass', data=df1)

sns.barplot(x='pclass', y='age', hue='sex', data=df1)

sns.barplot(x='sex', y='fare',data=df1)

sns.barplot(x='age', y='fare',data=df1)

sns.countplot(x='sex', data=df1)

df2=sns.load_dataset('titanic')

df2.head()

sns.catplot(x='embarked', y='age', hue='survived', data=df2)

sns.violinplot(x='sex', y='age', data=df2)

sns.stripplot(x='sex',y='age', data=df2)

sns.stripplot(x='sex',y='age', hue='survived', data=df2)

sns.stripplot(x='sex',y='age', hue='survived', data=df2, split=True)

sns.swarmplot(x='sex', y='age', data=df2, hue='survived')

sns.swarmplot(x='sex', y='age', data=df2, hue='survived', split=True)

sns.swarmplot(x='pclass', y='age', data=df2, hue='survived', split=True)

sns.violinplot(x='sex', y='age', data=df2)
sns.swarmplot(x='sex', y='age', data=df2, hue='survived',color='black' ,split=True)

